# Generated by Django 6.0.6 on 2026-06-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('status_code', models.PositiveIntegerField(verbose_name='Código Estado')),
                ('response_message', models.TextField(blank=True, verbose_name='Mensaje Respuesta')),
                ('records_updated', models.PositiveIntegerField(default=0, verbose_name='Registros Actualizados')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Sincronización')),
            ],
            options={
                'verbose_name': 'Log de Sincronización API',
                'verbose_name_plural': 'Logs de Sincronización API',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre Archivo')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash Archivo')),
                ('rows_imported', models.PositiveIntegerField(default=0, verbose_name='Filas Importadas')),
                ('status', models.CharField(choices=[('SUCCESS', 'Éxito'), ('PARTIAL', 'Parcial'), ('ERROR', 'Error')], max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Importación')),
            ],
            options={
                'verbose_name': 'Log de Importación',
                'verbose_name_plural': 'Logs de Importación',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signo_puntos', models.PositiveIntegerField(default=1, verbose_name='Puntos Signo 1X2')),
                ('diferencia_puntos', models.PositiveIntegerField(default=2, verbose_name='Puntos Diferencia Goles')),
                ('exacto_puntos', models.PositiveIntegerField(default=5, verbose_name='Puntos Resultado Exacto')),
                ('posicion_grupo_puntos', models.PositiveIntegerField(default=3, verbose_name='Puntos Posición Grupo')),
                ('equipo_ronda_puntos', models.PositiveIntegerField(default=2, verbose_name='Puntos Equipo por Ronda')),
                ('campeon_puntos', models.PositiveIntegerField(default=10, verbose_name='Puntos Campeón')),
                ('subcampeon_puntos', models.PositiveIntegerField(default=5, verbose_name='Puntos Subcampeón')),
                ('tercer_puesto_puntos', models.PositiveIntegerField(default=3, verbose_name='Puntos Tercer Puesto')),
                ('pichichi_puntos', models.PositiveIntegerField(default=7, verbose_name='Puntos Pichichi')),
                ('mvp_puntos', models.PositiveIntegerField(default=5, verbose_name='Puntos MVP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de Puntuación',
                'verbose_name_plural': 'Configuraciones de Puntuación',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('group', models.CharField(max_length=2, verbose_name='Grupo')),
                ('group_position', models.PositiveIntegerField(verbose_name='Posición en grupo')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji bandera')),
                ('fifa_code', models.CharField(blank=True, max_length=10, verbose_name='Código FIFA')),
            ],
            options={
                'verbose_name': 'Selección',
                'verbose_name_plural': 'Selecciones',
                'ordering': ['group', 'group_position'],
            },
        ),
        migrations.CreateModel(
            name='StandingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntos Totales')),
                ('group_stage_points', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntos Fase Grupos')),
                ('knockout_points', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntos Eliminatoria')),
                ('special_points', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntos Especiales')),
                ('exact_predictions', models.PositiveIntegerField(default=0, verbose_name='Predicciones Exactas')),
                ('sign_predictions', models.PositiveIntegerField(default=0, verbose_name='Aciertos Signo')),
                ('total_predictions', models.PositiveIntegerField(default=0, verbose_name='Total Predicciones')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Snapshot')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='pool.participant', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['-total_points', '-exact_predictions'],
            },
        ),
        migrations.CreateModel(
            name='ScorerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Nombre Jugador')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Goles')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Asistencias')),
                ('is_mvp', models.BooleanField(default=False, verbose_name='Es MVP')),
                ('is_golden_boot', models.BooleanField(default=False, verbose_name='Es Bota de Oro')),
                ('is_golden_ball', models.BooleanField(default=False, verbose_name='Es Balón de Oro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.team', verbose_name='Selección')),
            ],
            options={
                'verbose_name': 'Estadística Jugador',
                'verbose_name_plural': 'Estadísticas Jugadores',
                'ordering': ['-goals', '-assists'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles Local')),
                ('away_goals', models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles Visitante')),
                ('match_date', models.DateTimeField(verbose_name='Fecha del partido')),
                ('stage', models.CharField(choices=[('GROUP_STAGE', 'Fase de Grupos'), ('ROUND_OF_16', 'Dieciseisavos'), ('QUARTER_FINALS', 'Cuartos de Final'), ('SEMI_FINALS', 'Semifinales'), ('THIRD_PLACE', 'Tercer Puesto'), ('FINAL', 'Final')], default='GROUP_STAGE', max_length=20, verbose_name='Fase')),
                ('group_name', models.CharField(blank=True, max_length=5, verbose_name='Grupo')),
                ('matchday', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jornada')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('TIMED', 'Horario confirmado'), ('IN_PLAY', 'En juego'), ('PAUSED', 'Entretiempo'), ('FINISHED', 'Finalizado'), ('POSTPONED', 'Pospuesto'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20, verbose_name='Estado')),
                ('api_match_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID API')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='pool.team', verbose_name='Visitante')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='pool.team', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_home_goals', models.PositiveIntegerField(verbose_name='Pred. Goles Local')),
                ('pred_away_goals', models.PositiveIntegerField(verbose_name='Pred. Goles Visitante')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntos')),
                ('score_breakdown', models.JSONField(default=dict, verbose_name='Desglose de puntos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pool.match', verbose_name='Partido')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pool.participant', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['match__match_date'],
                'unique_together': {('participant', 'match')},
            },
        ),
        migrations.CreateModel(
            name='SpecialPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('CHAMPION', 'Campeón'), ('RUNNER_UP', 'Subcampeón'), ('THIRD_PLACE', 'Tercer Puesto'), ('GOLDEN_BOOT', 'Bota de Oro (Pichichi)'), ('GOLDEN_BALL', 'Balón de Oro (MVP)')], max_length=20, verbose_name='Tipo')),
                ('player_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre Jugador')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntos')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_predictions', to='pool.participant', verbose_name='Participante')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_predictions', to='pool.team', verbose_name='Selección')),
            ],
            options={
                'verbose_name': 'Predicción Especial',
                'verbose_name_plural': 'Predicciones Especiales',
                'unique_together': {('participant', 'prediction_type')},
            },
        ),
    ]
