# Generated by Django 6.0.6 on 2026-06-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisynclog',
            options={'ordering': ['-synced_at'], 'verbose_name': 'API Sync Log', 'verbose_name_plural': 'API Sync Logs'},
        ),
        migrations.AlterModelOptions(
            name='importlog',
            options={'ordering': ['-imported_at'], 'verbose_name': 'Import Log', 'verbose_name_plural': 'Import Logs'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['name'], 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['match__match_date'], 'verbose_name': 'Prediction', 'verbose_name_plural': 'Predictions'},
        ),
        migrations.AlterModelOptions(
            name='scorerstat',
            options={'ordering': ['-goals', '-assists'], 'verbose_name': 'Scorer Stat', 'verbose_name_plural': 'Scorer Stats'},
        ),
        migrations.AlterModelOptions(
            name='scoringconfig',
            options={'verbose_name': 'Scoring Config', 'verbose_name_plural': 'Scoring Configs'},
        ),
        migrations.AlterModelOptions(
            name='specialprediction',
            options={'verbose_name': 'Special Prediction', 'verbose_name_plural': 'Special Predictions'},
        ),
        migrations.AlterModelOptions(
            name='standingsnapshot',
            options={'ordering': ['-total_points', '-exact_predictions'], 'verbose_name': 'Standing', 'verbose_name_plural': 'Standings'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['group', 'group_position'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='apisynclog',
            name='records_updated',
            field=models.PositiveIntegerField(default=0, verbose_name='Records Updated'),
        ),
        migrations.AlterField(
            model_name='apisynclog',
            name='response_message',
            field=models.TextField(blank=True, verbose_name='Response Message'),
        ),
        migrations.AlterField(
            model_name='apisynclog',
            name='status_code',
            field=models.PositiveIntegerField(verbose_name='Status Code'),
        ),
        migrations.AlterField(
            model_name='apisynclog',
            name='synced_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Synced At'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='File Hash'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Imported At'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='rows_imported',
            field=models.PositiveIntegerField(default=0, verbose_name='Rows Imported'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('ERROR', 'Error')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='match',
            name='api_match_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='API ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goals',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Away Goals'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='pool.team', verbose_name='Away Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='group_name',
            field=models.CharField(blank=True, max_length=5, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goals',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Home Goals'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='pool.team', verbose_name='Home Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Synced'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(verbose_name='Match Date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Matchday'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('GROUP_STAGE', 'Group Stage'), ('ROUND_OF_16', 'Round of 16'), ('QUARTER_FINALS', 'Quarter Finals'), ('SEMI_FINALS', 'Semi Finals'), ('THIRD_PLACE', 'Third Place'), ('FINAL', 'Final')], default='GROUP_STAGE', max_length=20, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TIMED', 'Timed'), ('IN_PLAY', 'In Play'), ('PAUSED', 'Half Time'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='Avatar URL'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pool.match', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pool.participant', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pred_away_goals',
            field=models.PositiveIntegerField(verbose_name='Pred. Away Goals'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pred_home_goals',
            field=models.PositiveIntegerField(verbose_name='Pred. Home Goals'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='score_breakdown',
            field=models.JSONField(default=dict, verbose_name='Score Breakdown'),
        ),
        migrations.AlterField(
            model_name='scorerstat',
            name='assists',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Assists'),
        ),
        migrations.AlterField(
            model_name='scorerstat',
            name='goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Goals'),
        ),
        migrations.AlterField(
            model_name='scorerstat',
            name='is_golden_ball',
            field=models.BooleanField(default=False, verbose_name='Is Golden Ball'),
        ),
        migrations.AlterField(
            model_name='scorerstat',
            name='is_golden_boot',
            field=models.BooleanField(default=False, verbose_name='Is Golden Boot'),
        ),
        migrations.AlterField(
            model_name='scorerstat',
            name='is_mvp',
            field=models.BooleanField(default=False, verbose_name='Is MVP'),
        ),
        migrations.AlterField(
            model_name='scorerstat',
            name='player_name',
            field=models.CharField(max_length=100, verbose_name='Player Name'),
        ),
        migrations.AlterField(
            model_name='scorerstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='campeon_puntos',
            field=models.PositiveIntegerField(default=10, verbose_name='Champion Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='diferencia_puntos',
            field=models.PositiveIntegerField(default=2, verbose_name='Goal Difference Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='equipo_ronda_puntos',
            field=models.PositiveIntegerField(default=2, verbose_name='Team per Round Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='exacto_puntos',
            field=models.PositiveIntegerField(default=5, verbose_name='Exact Score Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='mvp_puntos',
            field=models.PositiveIntegerField(default=5, verbose_name='MVP Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='pichichi_puntos',
            field=models.PositiveIntegerField(default=7, verbose_name='Top Scorer Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='posicion_grupo_puntos',
            field=models.PositiveIntegerField(default=3, verbose_name='Group Position Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='signo_puntos',
            field=models.PositiveIntegerField(default=1, verbose_name='Sign 1X2 Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='subcampeon_puntos',
            field=models.PositiveIntegerField(default=5, verbose_name='Runner Up Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='tercer_puesto_puntos',
            field=models.PositiveIntegerField(default=3, verbose_name='Third Place Points'),
        ),
        migrations.AlterField(
            model_name='specialprediction',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_predictions', to='pool.participant', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='specialprediction',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Player Name'),
        ),
        migrations.AlterField(
            model_name='specialprediction',
            name='prediction_type',
            field=models.CharField(choices=[('CHAMPION', 'Champion'), ('RUNNER_UP', 'Runner Up'), ('THIRD_PLACE', 'Third Place'), ('GOLDEN_BOOT', 'Golden Boot (Top Scorer)'), ('GOLDEN_BALL', 'Golden Ball (MVP)')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='specialprediction',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='specialprediction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_predictions', to='pool.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='exact_predictions',
            field=models.PositiveIntegerField(default=0, verbose_name='Exact Predictions'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='group_stage_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Group Stage Points'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='knockout_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Knockout Points'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='pool.participant', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='sign_predictions',
            field=models.PositiveIntegerField(default=0, verbose_name='Sign Predictions'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Snapshot Date'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='special_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Special Points'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Points'),
        ),
        migrations.AlterField(
            model_name='standingsnapshot',
            name='total_predictions',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Predictions'),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=10, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='team',
            name='fifa_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='FIFA Code'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=10, verbose_name='Flag Emoji'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(max_length=2, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group_position',
            field=models.PositiveIntegerField(verbose_name='Group Position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
