# Generated by Django 6.0.6 on 2026-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_alter_apisynclog_options_alter_importlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringconfig',
            name='diferencia_puntos',
        ),
        migrations.RemoveField(
            model_name='scoringconfig',
            name='equipo_ronda_puntos',
        ),
        migrations.RemoveField(
            model_name='scoringconfig',
            name='exacto_puntos',
        ),
        migrations.RemoveField(
            model_name='scoringconfig',
            name='mvp_puntos',
        ),
        migrations.RemoveField(
            model_name='scoringconfig',
            name='pichichi_puntos',
        ),
        migrations.RemoveField(
            model_name='scoringconfig',
            name='posicion_grupo_puntos',
        ),
        migrations.RemoveField(
            model_name='scoringconfig',
            name='signo_puntos',
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='balon_bronce_puntos',
            field=models.PositiveIntegerField(default=5, verbose_name='Bronze Ball Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='balon_oro_puntos',
            field=models.PositiveIntegerField(default=20, verbose_name='Golden Ball Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='balon_plata_puntos',
            field=models.PositiveIntegerField(default=10, verbose_name='Silver Ball Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='bota_bronce_puntos',
            field=models.PositiveIntegerField(default=5, verbose_name='Bronze Boot Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='bota_oro_puntos',
            field=models.PositiveIntegerField(default=20, verbose_name='Golden Boot Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='bota_plata_puntos',
            field=models.PositiveIntegerField(default=10, verbose_name='Silver Boot Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='clasificado_final_puntos',
            field=models.PositiveIntegerField(default=20, verbose_name='Qualifies Final Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='clasificado_qf_puntos',
            field=models.PositiveIntegerField(default=10, verbose_name='Qualifies QF Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='clasificado_r16_puntos',
            field=models.PositiveIntegerField(default=5, verbose_name='Qualifies R16 Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='clasificado_sf_puntos',
            field=models.PositiveIntegerField(default=15, verbose_name='Qualifies SF Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='clasificado_tp_puntos',
            field=models.PositiveIntegerField(default=15, verbose_name='Qualifies Third Place Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='final_exacto_puntos',
            field=models.PositiveIntegerField(default=40, verbose_name='Final Exact Score Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='final_signo_puntos',
            field=models.PositiveIntegerField(default=25, verbose_name='Final Sign Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='group_clasificado_puntos',
            field=models.PositiveIntegerField(default=2, verbose_name='Group Qualifies for R16 Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='group_diferencia_puntos',
            field=models.PositiveIntegerField(default=1, verbose_name='Group Goal Difference Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='group_exacto_puntos',
            field=models.PositiveIntegerField(default=2, verbose_name='Group Exact Score Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='group_posicion_puntos',
            field=models.PositiveIntegerField(default=1, verbose_name='Group Position Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='group_signo_puntos',
            field=models.PositiveIntegerField(default=2, verbose_name='Group Sign 1X2 Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='qf_exacto_puntos',
            field=models.PositiveIntegerField(default=9, verbose_name='QF Exact Score Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='qf_signo_puntos',
            field=models.PositiveIntegerField(default=5, verbose_name='QF Sign Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='r16_exacto_puntos',
            field=models.PositiveIntegerField(default=5, verbose_name='R16 Exact Score Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='r16_signo_puntos',
            field=models.PositiveIntegerField(default=3, verbose_name='R16 Sign Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='sf_exacto_puntos',
            field=models.PositiveIntegerField(default=15, verbose_name='SF Exact Score Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='sf_signo_puntos',
            field=models.PositiveIntegerField(default=10, verbose_name='SF Sign Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='tp_exacto_puntos',
            field=models.PositiveIntegerField(default=30, verbose_name='Third Place Exact Score Points'),
        ),
        migrations.AddField(
            model_name='scoringconfig',
            name='tp_signo_puntos',
            field=models.PositiveIntegerField(default=15, verbose_name='Third Place Sign Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='campeon_puntos',
            field=models.PositiveIntegerField(default=50, verbose_name='Champion Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='subcampeon_puntos',
            field=models.PositiveIntegerField(default=25, verbose_name='Runner Up Points'),
        ),
        migrations.AlterField(
            model_name='scoringconfig',
            name='tercer_puesto_puntos',
            field=models.PositiveIntegerField(default=15, verbose_name='Third Place Points'),
        ),
        migrations.AlterField(
            model_name='specialprediction',
            name='prediction_type',
            field=models.CharField(choices=[('CHAMPION', 'Champion'), ('RUNNER_UP', 'Runner Up'), ('THIRD_PLACE', 'Third Place'), ('GOLDEN_BOOT', 'Golden Boot (Top Scorer)'), ('GOLDEN_BOOT_2', 'Silver Boot (2nd Top Scorer)'), ('GOLDEN_BOOT_3', 'Bronze Boot (3rd Top Scorer)'), ('GOLDEN_BALL', 'Golden Ball (MVP)'), ('GOLDEN_BALL_2', 'Silver Ball (2nd MVP)'), ('GOLDEN_BALL_3', 'Bronze Ball (3rd MVP)')], max_length=20, verbose_name='Type'),
        ),
    ]
