# Generated by Django 6.0.6 on 2026-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_scoringconfig_special_predictions_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_goals_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Goals Synced'),
        ),
    ]
