# Generated by Django 6.0.6 on 2026-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_match_last_goals_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='thesportsdb_event_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TheSportsDB Event ID'),
        ),
    ]
